# version: '3.8'

# services:
#   fastapi-app:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     restart: always 

version: '3.8'

services:
  backend1:
    build: .
    container_name: backend1
    ports:
      - "8001:8000"

  backend2:
    build: .
    container_name: backend2
    ports:
      - "8002:8000"

  backend3:
    build: .
    container_name: backend3
    ports:
      - "8003:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3